version: '3'

services:
  irods-catalog-provider:
    container_name: irods-catalog-provider
    build:
        context: .
        dockerfile: Dockerfile.provider
    hostname: icat.example.org
    networks:
      irodsnet:
        aliases:
          - icat.example.org
    ports:
      - "1247:1247"
      #- "5432:5432"
      #- "20000-21999"

  irods-catalog-consumer-resource1:
    container_name: irods-catalog-consumer-resource1
    build:
        context: .
        dockerfile: Dockerfile.consumer
    hostname: resource1.example.org
    networks:
      irodsnet:
        aliases:
          - resource1.example.org
    depends_on:
      - irods-catalog-provider

  ngrep-viewer:
    container_name: ngrep-viewer 
    image: nicolaka/netshoot 
    depends_on:
      - irods-catalog-provider
      - irods-catalog-consumer-resource1
    command: ngrep -W byline 1247

networks:
   irodsnet:
    driver: bridge
  
